language: cpp

os:
  - linux

services:
  - docker

before_script:
  - docker run -ti --rm -v $PWD:/qflex:ro debian:bullseye /bin/bash -c "apt update && apt install -y yapf3 clang-format && bash /qflex/scripts/check_format.sh"
  - docker-compose build

script:
  - docker run -ti --rm qflex-tests:latest
  - docker run -ti --rm qflex-py-tests:latest
  - docker run -ti --rm qflex:latest /qflex/config/circuits/bristlecone_48_1-24-1_0.txt /qflex/config/ordering/bristlecone_48.txt /qflex/config/grid/bristlecone_48.txt
