version: "3"
services:
  qflex:
    image: qflex
    container_name: qflex
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - OMP_NUM_THREADS=${OMP_NUM_THREADS}
        - QFLEX_BRANCH=${QFLEX_BRANCH}
        - QFLEX_REPO=${QFLEX_REPO}
  qflex-cxx-tests:
    image: qflex-cxx-tests
    container_name: qflex-cxx-tests
    build:
      context: ./
      dockerfile: tests/src/Dockerfile
    depends_on:
    - qflex
  qflex-py-tests:
    image: qflex-py-tests
    container_name: qflex-py-tests
    build:
      context: ./
      dockerfile: tests/python/Dockerfile
    depends_on:
    - qflex
